### ISSUE TITLE
global name 'curr_state' is not defined

### ISSUE THREAD

**Issue by StevenLOL** [hardikbansal/Qlearning#1]
Got following error, when invoke "python flappy_dqn_gym.py"
```
...
Total rewards in episode 194 is 3.8 total number of steps are 9555
Total rewards in episode 195 is 3.8 total number of steps are 9604
Total rewards in episode 196 is 3.8 total number of steps are 9653
Total rewards in episode 197 is 3.8 total number of steps are 9702
Total rewards in episode 198 is 3.8 total number of steps are 9751
Total rewards in episode 199 is 3.8 total number of steps are 9800
Total rewards in episode 200 is 3.8 total number of steps are 9849
Total rewards in episode 201 is 3.8 total number of steps are 9898
Total rewards in episode 202 is 3.8 total number of steps are 9947
Total rewards in episode 203 is 3.8 total number of steps are 9996
Traceback (most recent call last):
  File "flappy_dqn_gym.py", line 287, in <module>
    main()
  File "flappy_dqn_gym.py", line 283, in main
    mod.train()
  File "flappy_dqn_gym.py", line 166, in train
    temp_action = self.policy(sess, "e_greedy")
  File "flappy_dqn_gym.py", line 111, in policy
    feed_dict={self.main_net.input_state:np.reshape(curr_state,[-1, self.state_size])})
NameError: global name 'curr_state' is not defined
```

**Comment by hardikbansal** [comment]
Corrected it. I forgot to push the commit changes earlier. It should be working now.
